### ISSUE TITLE
duplicate class tree

### ISSUE THREAD

**Issue by vinutah** [ajanthav10/MachineLearning#1]
https://github.com/ajanthav10/MachineLearning/blob/584a782776a86fb448222c191c440a1756e9f454/Decision%20Tree/ID3.py#L104

**Comment by ajanthav10** [comment]
Dont do create issue. I must submit this for my assignment ma . Need help
with scikit version. I checked online , almost all examples have only
splitting of data. I did this myself but giving error . Help please !😭😢
